Refactor GAM commands to use variable syntax

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -900,18 +900,18 @@ jobs:
 
           # cleanup old runs
           run_gam config enable_dasa false save
-          run_gam config csv_output_row_filter "name:regex:gha_test_${JID}_" print vaultholds | run_gam csv - gam delete vaulthold "id:~~holdId~~" matter "id:~~matterId~~" || if [ $? != 55 ]; then exit $?; fi 
-          run_gam config csv_output_row_filter "name:regex:gha_test_${JID}_" print vaultmatters matterstate OPEN | run_gam csv - gam update vaultmatter "id:~~matterId~~" action close
-          run_gam config csv_output_row_filter "name:regex:gha_test_${JID}_" print vaultmatters matterstate CLOSED | run_gam csv - gam update vaultmatter "id:~~matterId~~" action delete
-          run_gam config csv_output_row_filter "Emails.1.address:regex:^gha_test-${JID}_" print contacts | run_gam csv - gam delete contact ~ContactID
+          $gam config csv_output_row_filter "name:regex:gha_test_${JID}_" print vaultholds | $gam csv - gam delete vaulthold "id:~~holdId~~" matter "id:~~matterId~~" || if [ $? != 55 ]; then exit $?; fi 
+          $gam config csv_output_row_filter "name:regex:gha_test_${JID}_" print vaultmatters matterstate OPEN | $gam csv - gam update vaultmatter "id:~~matterId~~" action close
+          $gam config csv_output_row_filter "name:regex:gha_test_${JID}_" print vaultmatters matterstate CLOSED | $gam csv - gam update vaultmatter "id:~~matterId~~" action delete
+          $gam config csv_output_row_filter "Emails.1.address:regex:^gha_test-${JID}_" print contacts | $gam csv - gam delete contact ~ContactID
           run_gam config enable_dasa true save
-          run_gam config csv_output_row_filter "name:regex:gha_test_${JID}_" print features | run_gam csv - gam delete feature ~name
-          run_gam config csv_output_row_filter "name:regex:^gha_test_${JID}_" user $gam_user print shareddrives asadmin | run_gam csv - gam user $gam_user delete shareddrive ~id nukefromorbit
-          run_gam print users query "gha.jid=$JID" | run_gam csv - gam delete user ~primaryEmail
-          run_gam config csv_output_row_filter "name:regex:^gha_test_${JID}_" print ous fromparent "aaaGithub Actions" | run_gam csv - gam delete ou ~orgUnitId
-          run_gam config csv_output_row_filter "email:regex:^gha_test_${JID}_" print cigroups | run_gam csv - gam delete cigroup ~email
-          run_gam config csv_output_row_filter "resourceId:regex:^gha_test_${JID}_" print resources | run_gam csv - gam delete resource ~resourceId
-          run_gam config csv_output_row_filter "buildingId:regex:^gha_test_${JID}_" print buildings | run_gam csv - gam delete building ~buildingId
+          $gam config csv_output_row_filter "name:regex:gha_test_${JID}_" print features | $gam csv - gam delete feature ~name
+          $gam config csv_output_row_filter "name:regex:^gha_test_${JID}_" user $gam_user print shareddrives asadmin | $gam csv - gam user $gam_user delete shareddrive ~id nukefromorbit
+          $gam print users query "gha.jid=$JID" | $gam csv - gam delete user ~primaryEmail
+          $gam config csv_output_row_filter "name:regex:^gha_test_${JID}_" print ous fromparent "aaaGithub Actions" | $gam csv - gam delete ou ~orgUnitId
+          $gam config csv_output_row_filter "email:regex:^gha_test_${JID}_" print cigroups | $gam csv - gam delete cigroup ~email
+          $gam config csv_output_row_filter "resourceId:regex:^gha_test_${JID}_" print resources | $gam csv - gam delete resource ~resourceId
+          $gam config csv_output_row_filter "buildingId:regex:^gha_test_${JID}_" print buildings | $gam csv - gam delete building ~buildingId
 
           echo "Creating OrgUnit ${newou}"
           run_gam create ou "${newou}"
@@ -980,7 +980,7 @@ jobs:
           run_gam users "$newbase-bulkuser-4 $newbase-bulkuser-5 $newbase-bulkuser-6" trash messages query in:anywhere maxtotrash 99999 doit || if [ $? != 60 ]; then exit $?; fi # expect a 60 return code (no messages)
           run_gam users "$newbase-bulkuser-7 $newbase-bulkuser-8 $newbase-bulkuser-9" modify messages query in:anywhere maxtomodify 99999 addlabel IMPORTANT addlabel STARRED doit || if [ $? != 60 ]; then exit $?; fi # expect a 60 return code (no messages)
           run_gam user $newuser delete label --ALL_LABELS--
-          run_gam config csv_output_row_filter "name:regex:gha-test-${JID}" print features | run_gam csv - gam delete feature ~name
+          $gam config csv_output_row_filter "name:regex:gha-test-${JID}" print features | $gam csv - gam delete feature ~name
           run_gam create feature name VC-$newbase
           run_gam create feature name Whiteboard-$newbase
           run_gam create building "My Building - $newbase" id $newbuilding floors 1,2,3,4,5,6,7,8,9,10,11,12,14,15 description "No 13th floor here..."
@@ -988,12 +988,12 @@ jobs:
           run_gam info resource $newresource
           run_gam user $newuser add drivefile drivefilename "TPS Reports" mimetype gfolder
           run_gam user $newuser show filelist
-          run_gam calendar $gam_user printacl | run_gam csv - gam calendar $gam_user delete ~id # clear ACLs
+          $gam calendar $gam_user printacl | $gam csv - gam calendar $gam_user delete ~id # clear ACLs
           run_gam calendar $gam_user add read domain
           run_gam calendar $gam_user add freebusy default
           run_gam calendar $gam_user add editor $newuser
           run_gam calendar $gam_user showacl
-          run_gam calendar $gam_user printacl | run_gam csv - gam calendar $gam_user delete ~id
+          $gam calendar $gam_user printacl | $gam csv - gam calendar $gam_user delete ~id
           run_gam calendar $gam_user addevent summary "GHA test event" start +1h end +2h attendee $newgroup hangoutsmeet guestscanmodify true sendupdates all
           run_gam calendar $gam_user printevents after -0d
           run_gam config enable_dasa false save
@@ -1003,7 +1003,7 @@ jobs:
           run_gam print vaultholds matter $matterid
           run_gam print vaultcount matter $matterid corpus mail everyone todrive tdnobrowser
           run_gam create vaultexport matter $matterid name "GHA export $newbase" corpus mail ou "$newou"
-          run_gam print exports matter $matterid | run_gam csv - gam info export $matterid id:~~id~~
+          $gam print exports matter $matterid | $gam csv - gam info export $matterid id:~~id~~
           run_gam config enable_dasa true save
           run_gam csv sample.csv gam user ~email add calendar id:$newresource
           run_gam delete resource $newresource
@@ -1021,19 +1021,19 @@ jobs:
           run_gam config enable_dasa false save
           download_dir="${RUNNER_TEMP}/TEMP_DELETE_ME"
           mkdir -v "$download_dir"
-          run_gam print exports matter $matterid | run_gam csv - gam download export $matterid id:~~id~~ targetfolder "$download_dir"
+          $gam print exports matter $matterid | $gam csv - gam download export $matterid id:~~id~~ targetfolder "$download_dir"
           rm -rvf "$download_dir"
           run_gam delete hold "GHA hold $newbase" matter $matterid
           run_gam update matter $matterid action close
           run_gam update matter $matterid action delete
           # shakes off vault hold on user so we can delete
-          run_gam print users query "email:${newuser}" orgunitpath | run_gam csv - gam update user ~primaryEmail ou ~orgUnitPath
+          $gam print users query "email:${newuser}" orgunitpath | $gam csv - gam update user ~primaryEmail ou ~orgUnitPath
           run_gam user $newuser show holds || if [ $? != 55 ]; then exit $?; fi # expect a 55 return code
           export sn="$JID$JID$JID$JID-$(openssl rand -base64 32 | sed 's/[^a-zA-Z0-9]//g')"
           run_gam create device serialnumber $sn devicetype android
           run_gam delete contacts emailmatchpattern "^${newbase}@example.com$"
           run_gam config enable_dasa true save
-          run_gam print users query "gha.jid=$JID" | run_gam csv - gam delete user ~primaryEmail  || if [ $? != 50 ]; then exit $?; fi # expect a 50 return code (vault hold on user)
+          $gam print users query "gha.jid=$JID" | $gam csv - gam delete user ~primaryEmail  || if [ $? != 50 ]; then exit $?; fi # expect a 50 return code (vault hold on user)
           run_gam print mobile
           run_gam print devices clientstates
           run_gam print browsers
@@ -1045,10 +1045,10 @@ jobs:
           #run_gam report users fields accounts:is_less_secure_apps_access_allowed,gmail:last_imap_time,gmail:last_pop_time filters "accounts:last_login_time>2025-01-01T00:00:00.000Z" todrive tdnobrowser
           run_gam report users todrive tdnobrowser
           run_gam report admin start -3d todrive tdnobrowser
-          run_gam print devices nopersonaldevices nodeviceusers filter "serial:$JID$JID$JID$JID-" | run_gam csv - gam delete device id ~name
+          $gam print devices nopersonaldevices nodeviceusers filter "serial:$JID$JID$JID$JID-" | $gam csv - gam delete device id ~name
           run_gam config enable_dasa false save
           run_gam print userinvitations
-          run_gam print userinvitations | run_gam csv - gam send userinvitation ~name
+          $gam print userinvitations | $gam csv - gam send userinvitation ~name
           run_gam config enable_dasa false save
           run_gam create caalevel "zzz_${newbase}" basic condition ipsubnetworks 1.1.1.1/32,2.2.2.2/32 endcondition
           run_gam print caalevels
